web/router.ex
defmodule Featureyard.Router do
  use Featureyard.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Featureyard do
    pipe_through [:browser, :browser_session]

    get "/", PageController, :index

    get    "/sign_in" , SessionController, :new   , as: :sign_in
    post   "/sign_in" , SessionController, :create, as: :sign_in

    get    "/sign_out", SessionController, :delete, as: :sign_out
    delete "/sign_out", SessionController, :delete, as: :sign_out

    get    "/sign_up" , UserController, :new   , as: :sign_up
    post   "/sign_up" , UserController, :create, as: :sign_up

    get    "/user"   , UserController, :show  , as: :user

    put    "/clients/:id/key", ClientController, :reset_key, as: :reset_key
    resources "/clients", ClientController do
      resources "/features", FeatureController, except: [:show] do
        resources "/audiences", AudienceController
      end
    end
  end

  # Other scopes may use custom stacks.
  scope "/api", Featureyard do
    pipe_through :api

    get "/features", Api.FeatureController, :index
  end
end

web/views/layout_view.ex
defmodule Featureyard.LayoutView do
  use Featureyard.Web, :view
end

web/templates/layout/_alert_notification.eex
<%= if @alert do %>
<div class="row">
  <div class="col s12 m6">
    <div class="card red light-5">
      <div class="card-content white-text">
        <span class="card-title">Alert</span>
        <p><%= @alert %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

web/templates/layout/_alert_notification.html.eex
<%= if @alert do %>
<script>
(function() { Materialize.toast("<%= @alert %>", 4000)})();
</script>
<% end %>

web/templates/layout/_info_notification.eex
<%= if @info do %>
<div class="row">
  <div class="col s12 m6">
    <div class="card blue darken-1">
      <div class="card-content white-text">
        <span class="card-title">Info</span>
        <p><%= @info %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

web/templates/layout/_info_notification.html.eex
<%= if @info do %>
<script>
(function() { Materialize.toast("<%= @info %>", 4000)})()
</script>
<% end %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="theme-color" content="3f51b5">

  <title>Feature Yard</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono|Roboto" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</head>

<body>
  <nav class="light-blue">
    <div class="nav-wrapper container">
      <a href="/" class="brand-logo">Feature Yard</a>
      <ul class="right hide-on-med-and-down">
        <%= if Guardian.Plug.current_resource(@conn) do %>
        <li><%= link "Clients", to: client_path(@conn, :index) %></li>
        <li><%= link "Sign Out", to: sign_out_path(@conn, :delete), method: :delete %></li>
        <% else %>
        <li><%= link "Sign In", to: sign_in_path(@conn, :new) %></li>
        <% end %>

      </ul>
      <ul class="side-nav" id="nav-mobile">
        <%= if Guardian.Plug.current_resource(@conn) do %>
        <li><%= link "Clients", to: client_path(@conn, :index) %></li>
        <li><%= link "Sign Out", to: sign_out_path(@conn, :delete), method: :delete %></li>
        <% else %>
        <li><%= link "Sign In", to: sign_in_path(@conn, :new) %></li>
        <% end %>
      </ul>
       <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div class="container">
    <%= render "_info_notification.html", info: get_flash(@conn, :info)  %>
    <%= render "_alert_notification.html", alert: get_flash(@conn, :error)  %>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

  </div> <!-- /container -->

</body>
</html>