web/router.ex
defmodule Featureyard.Router do
  use Featureyard.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Featureyard do
    pipe_through [:browser, :browser_session]

    get "/", PageController, :index

    get    "/sign_in" , SessionController, :new   , as: :sign_in
    post   "/sign_in" , SessionController, :create, as: :sign_in

    get    "/sign_out", SessionController, :delete, as: :sign_out
    delete "/sign_out", SessionController, :delete, as: :sign_out

    get    "/sign_up" , UserController, :new   , as: :sign_up
    post   "/sign_up" , UserController, :create, as: :sign_up

    get    "/user"   , UserController, :show  , as: :user

    put    "/clients/:id/key", ClientController, :reset_key, as: :reset_key
    resources "/clients", ClientController do
      resources "/features", FeatureController, except: [:show] do
        resources "/audiences", AudienceController
      end
    end
  end

  # Other scopes may use custom stacks.
  scope "/api", Featureyard do
    pipe_through :api

    get "/features", Api.FeatureController, :index
  end
end

web/models/client.ex
defmodule Featureyard.Client do
  use Featureyard.Web, :model

  schema "clients" do
    field :name, :string
    field :key, :string, default: UUID.uuid1()
    has_many :features, Featureyard.Feature, on_delete: :delete_all
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name])
    |> validate_required([:name])
  end
end

web/controllers/client_controller.ex
defmodule Featureyard.ClientController do
  use Featureyard.Web, :controller

  alias Featureyard.Client

  plug Guardian.Plug.EnsureAuthenticated, [handler: Featureyard.SessionController]

  def index(conn, _params) do
    clients = Repo.all(Client)
    render(conn, "index.html", clients: clients)
  end

  def new(conn, _params) do
    changeset = Client.changeset(%Client{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"client" => client_params}) do
    changeset = Client.changeset(%Client{}, client_params)

    case Repo.insert(changeset) do
      {:ok, _client} ->
        conn
        |> put_flash(:info, "Client created successfully.")
        |> redirect(to: client_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    client = Repo.get!(Client, id)
    client_key = Base.encode64(client.key)
    render(conn, "show.html", client: client, base64_key: client_key)
  end

  def edit(conn, %{"id" => id}) do
    client = Repo.get!(Client, id)
    changeset = Client.changeset(client)
    render(conn, "edit.html", client: client, changeset: changeset)
  end

  def update(conn, %{"id" => id, "client" => client_params}) do
    client = Repo.get!(Client, id)
    changeset = Client.changeset(client, client_params)

    case Repo.update(changeset) do
      {:ok, client} ->
        conn
        |> put_flash(:info, "Client updated successfully.")
        |> redirect(to: client_path(conn, :show, client))
      {:error, changeset} ->
        render(conn, "edit.html", client: client, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    client = Repo.get!(Client, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(client)

    conn
    |> put_flash(:info, "Client deleted successfully.")
    |> redirect(to: client_path(conn, :index))
  end

  # PUT /clients/1/key
  def reset_key(conn, %{"id" => id}) do
    client = Repo.get! Client, id
    changeset = Client.changeset(client, %{key: UUID.uuid1()})
    case Repo.update(changeset) do
      {:ok, saved_client} ->
        conn
        |> put_flash(:info, "Client key regenerated successfully.")
        |> redirect(to: client_path(conn, :show, saved_client))
      {:error, _changeset} ->
        conn
        |> put_flash(:error, "Failed to regeneted key.")
        |> redirect(to: client_path(conn, :show, client))
    end
  end
end

web/views/client_view.ex
defmodule Featureyard.ClientView do
  use Featureyard.Web, :view
end

web/templates/client/edit.html.eex
<div class="row">
  <div class="col s12">
    <h2>Edit client</h2>
  </div>
</div>


<%= render "form.html", changeset: @changeset,
                        action: client_path(@conn, :update, @client) %>

web/templates/client/form.html.eex
<div class="row">
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
<div class="row">
                <div class="col s12">
                  <div class="card lix-purple lighten-3">
                    <div class="card-content white-text">
                      <span class="card-title">Ops!</span>
  <p>Oops, something went wrong! Please check the errors below.</p>
                    </div>
                  </div>
                </div>
              </div>
<% end %>

<div class="col s12">
  <div class="row">
    <div class="input-field col s12">
      <%= label f, :name %>
      <%= text_input f, :name, class: "red-input" %>
      <%= error_tag f, :name %>
    </div>

  </div>
</div>
<div class="row">
  <div class="col s12">
    <button class="btn btn-large waves-effect waves-light lix-purple hide-on-med-and-down" type="submit" name="action">Submit
      <i class="material-icons right">check</i>
    </button>
    <div class="fixed-action-btn hide-on-large-only" style="bottom: 24px; right: 24px;">
      <button type="submit" class="btn-floating btn-large lix-purple">
        <i class="large material-icons">check</i>
      </button>
    </div>
  </div>
</div>
<% end %>
</div>

web/templates/client/index.html.eex
<div class="row">
  <div class="col s12">
    <h2>My Clients</h2>
  </div>
</div>
<div class="row">
  <div class="col s12">
  <%= link "New client", to: client_path(@conn, :new), class: "btn lix-purple waves-effect waves-red" %>
</div>
</div>
<div class="row">
  <div class="col s12">
    <table class="responsive-table bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Options</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= for client <- @clients do %>
        <tr>
          <td><%= client.name %></td>
          <td>
            <%= link "Show", to: client_path(@conn, :show, client), class: "waves-effect waves-blue" %>
          </td>
          <td>
            <%= link "Features", to: client_feature_path(@conn, :index, client), class: "waves-effect waves-blue" %>
          </td>
          <td>
            <%= link "Edit", to: client_path(@conn, :edit, client), class: "waves-effect waves-blue" %>
          </td>
          <td>
            <%= link "Delete", to: client_path(@conn, :delete, client), method: :delete, data: [confirm: "Are you sure?"], class: "waves-effect waves-red" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

web/templates/client/new.html.eex
<div class="row">
  <div class="col s12">
    <h2>Add client</h2>
  </div>
</div>


<%= render "form.html", changeset: @changeset,
action: client_path(@conn, :create) %>

web/templates/client/show.html.eex
<div class="row">
  <div class="col s12">
    <h2><%= @client.name %></h2>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <div class="left-align">
      <%= link "Features", to: client_feature_path(@conn, :index, @client), class: "btn lix-purple waves-effect waves-red" %>
      &nbsp;
      <%= link "Edit client", to: client_path(@conn, :edit, @client), class: "btn lix-purple waves-effect waves-red" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s12 m7">
    <div class="card grey lighten-5">
      <div class="card-content grey-text darken-1">
        <span class="card-title">Client Key</span>
        <p>
          <code id="key-box" class="long-text"><%= @base64_key %></code>
        </p>
      </div>
      <div class="card-action">
        <button type="button" data-clipboard-target="#key-box" class="btn waves-effect waves-blue btn-card lix-text copyable">
          <i class="material-icons left">content_copy</i> Copy
        </button>
        <%= link raw("<i class='material-icons left'>refresh</i> Refresh"),
         to: reset_key_path(@conn, :reset_key, @client),
         class: "btn waves-effect waves-blue btn-card lix-text",
         method: :put %>
        </div>
      </div>
    </div>
  </div>