web/router.ex
defmodule Featureyard.Router do
  use Featureyard.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Featureyard do
    pipe_through [:browser, :browser_session]

    get "/", PageController, :index

    get    "/sign_in" , SessionController, :new   , as: :sign_in
    post   "/sign_in" , SessionController, :create, as: :sign_in

    get    "/sign_out", SessionController, :delete, as: :sign_out
    delete "/sign_out", SessionController, :delete, as: :sign_out

    get    "/sign_up" , UserController, :new   , as: :sign_up
    post   "/sign_up" , UserController, :create, as: :sign_up

    get    "/user"   , UserController, :show  , as: :user

    put    "/clients/:id/key", ClientController, :reset_key, as: :reset_key
    resources "/clients", ClientController do
      resources "/features", FeatureController, except: [:show] do
        resources "/audiences", AudienceController
      end
    end
  end

  # Other scopes may use custom stacks.
  scope "/api", Featureyard do
    pipe_through :api

    get "/features", Api.FeatureController, :index
  end
end

web/models/feature.ex
defmodule Featureyard.Feature do
  use Featureyard.Web, :model

  schema "features" do
    field :name, :string
    field :key, :string
    field :enabled, :boolean, default: false
    belongs_to :client, Featureyard.Client
    has_many :audiences, Featureyard.Audience, on_delete: :delete_all
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :key, :enabled, :client_id])
    |> validate_required([:name, :key, :enabled, :client_id])
  end
end

web/controllers/feature_controller.ex
defmodule Featureyard.FeatureController do
  use Featureyard.Web, :controller

  alias Featureyard.Feature
  alias Featureyard.Client
  alias Featureyard.Repo

  plug Guardian.Plug.EnsureAuthenticated, [handler: Featureyard.SessionController]

  def index(conn, %{"client_id" => client_id}) do
    client = Repo.get!(Client, client_id) |> Repo.preload(:features)
    conn |> render("index.html", client: client)
  end

  def new(conn, %{"client_id" => client_id}) do
    client = Repo.get!(Client, client_id)
    changeset = Feature.changeset(%Feature{client_id: client.id})
    render(conn, "new.html", changeset: changeset, client: client)
  end

  def create(conn, %{"feature" => feature_params, "client_id" => client_id}) do
    changeset = Feature.changeset(%Feature{}, feature_params)

    case Repo.insert(changeset) do
      {:ok, feature} ->
        loaded = Repo.preload(feature, :client)
        conn
        |> put_flash(:info, "Feature created successfully.")
        |> redirect(to: client_feature_path(conn, :index, loaded.client.id))
        {:error, changeset} ->
          render(conn, "new.html", changeset: changeset,
          client: %Client{id: client_id})
        end
      end

  def edit(conn, %{"id" => id, "client_id" => client_id}) do
    feature = Repo.get!(Feature, id) |> Repo.preload(:client)
    changeset = Feature.changeset(feature)
    render(conn, "edit.html", feature: feature, changeset: changeset, client: %Client{id: client_id})
  end

  def update(conn, %{"id" => id, "client_id" => client_id, "feature" => feature_params}) do
    feature = Repo.get!(Feature, id)
    changeset = Feature.changeset(feature, feature_params)

    case Repo.update(changeset) do
      {:ok, feature} ->
        loaded = Repo.preload feature, :client
        conn
        |> put_flash(:info, "Feature updated successfully.")
        |> redirect(to: client_feature_path(conn, :index, loaded.client))
        {:error, changeset} ->
          render(conn, "edit.html", feature: feature,
          changeset: changeset, client: %Client{id: client_id})
    end
  end

  def delete(conn, %{"id" => id}) do
    feature = Repo.get!(Feature, id)
    client = Repo.preload(feature ,:client)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(feature)

    conn
    |> put_flash(:info, "Feature deleted successfully.")
    |> redirect(to: client_feature_path(conn, :index, client))
    end
end

web/views/feature_view.ex
defmodule Featureyard.FeatureView do
  use Featureyard.Web, :view
end

web/templates/feature/edit.html.eex
<h2>Edit feature</h2>

<%= render "form.html", changeset: @changeset,
                        action: client_feature_path(@conn, :update, @client, @feature) %>

web/templates/feature/form.html.eex
<div class="row">
  <div class="col s12">
    <%= form_for @changeset, @action, fn f -> %>
    <%= if @changeset.action do %>
    <div class="row">
      <div class="col s12">
        <div class="card lix-purple lighten-3">
          <div class="card-content white-text">
            <span class="card-title">Ops!</span>
            <p>Oops, something went wrong! Please check the errors below.</p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <div class="row">
      <div class="input-field col s12">
        <%= label f, :name %>
        <%= text_input f, :name, class: "red-input" %>
        <%= error_tag f, :name %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= label f, :key %>
        <%= text_input f, :key, class: "red-input" %>
        <%= error_tag f, :key %>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <div class="switch">
          <label>
            Off
            <%= checkbox f, :enabled %>
            <span class="lever"></span>
            On
          </label>
        </div>
        <%= error_tag f, :enabled %>
      </div>
    </div>
    <div class="row margin-top-2x">
      <div class="col s12">
        <%= hidden_input f, :client_id %>
        <button class="btn btn-large waves-effect waves-light lix-purple hide-on-med-and-down" type="submit" name="action">Submit
          <i class="material-icons right">check</i>
        </button>
        <div class="fixed-action-btn hide-on-large-only" style="bottom: 24px; right: 24px;">
          <button type="submit" class="btn-floating btn-large lix-purple">
            <i class="large material-icons">check</i>
          </button>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>

web/templates/feature/index.html.eex
<div class="row">
  <div class="col s12">
    <h2>Features of <%= @client.name %></h2>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <%= link "New feature", to: client_feature_path(@conn, :new, @client), class: "btn lix-purple waves-effect waves-red" %>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <table class="responsive-table bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Key</th>
          <th>Enabled</th>
          <th>Options</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= for feature <- @client.features do %>
        <tr>
          <td><%= feature.name %></td>
          <td><code><%= feature.key %></code></td>
          <td class="">
            <%= if feature.enabled do %>
            <i class="teal-text material-icons">done</i>
            <% else %>
            <i class="red-grey-text material-icons">highlight_off</i>
            <% end %>
          </td>
          <td>
            <%= link "Audience", to: client_feature_audience_path(@conn, :index, feature.client_id, feature) %>
          </td>
          <td class="text-right">
            <%= link "Edit", to: client_feature_path(@conn, :edit, feature.client_id, feature), class: "waves-effect waves-blue" %>
          </td>
          <td class="text-right">
            <%= link "Remove", to: client_feature_path(@conn, :delete, feature.client_id, feature), method: :delete, data: [confirm: "Are you sure?"], class: "waves-effect waves-red" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <!-- features -->
  </div>

web/templates/feature/new.html.eex
<div class="row">
  <div class="col s12">
    <h2>New Feature</h2>
  </div>
</div>


<%= render "form.html", changeset: @changeset,
action: client_feature_path(@conn, :create, @client) %>

web/templates/feature/show.html.eex
<h2>Show feature</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @feature.name %>
  </li>

  <li>
    <strong>Key:</strong>
    <%= @feature.key %>
  </li>

  <li>
    <strong>Enabled:</strong>
    <%= @feature.enabled %>
  </li>

  <li>
    <strong>Client:</strong>
    <%= @feature.client_id %>
  </li>

</ul>

<%= link "Edit", to: client_feature_path(@conn, :edit, @feature.client_id, @feature) %>
<%= link "Back", to: client_feature_path(@conn, :index, @feature.client_id) %>